proxy:
  title: OpenStats
  port: 8080
  authentication: none
  hide-navbar: true
  landing-page: SingleApp

  docker:
    internal-networking: true

  specs:
    - id: OpenStats
      display-name: OpenStats
      container-image: konradkraemer/openstats:latest
      container-cmd: ["Rscript", "/srv/shiny-server/app.R"]
      container-network: sp-net

server:
  forward-headers-strategy: native

