Sys.setenv(RUN_MODE = "LOCAL")
if (!grepl("R", getwd())) setwd("OpenStats/R")
options(shiny.launch.browser = TRUE)
files <- list.files(".")
trash <- lapply(files, source)
app <- app()
shiny::shinyApp(app$ui, app$server)
